openapi: 3.0.0
servers:
  - url: 'http://localhost:8080/v2'
    description: localhost
info:
  title: Users server
  description: 'Rest services definition module for user'
  version: 1.0.0
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: users
    description: Operations about users
paths:
  /users:
    get:
      operationId: getAllUsers
      summary: 'Retrieve a current users'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      description: Get all users list
      tags:
        - users
components:
  schemas:
    User:
      title: a User
      description: A User who is purchasing
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phone:
          type: string
